version: 2.1
orbs:
  node: circleci/node@5.0.0
executors:
  node:
    docker:
      - image: cimg/node:17.5.0
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/lukeocodes/go-and-git-a-repo/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  setup-image:
    executor: node
    steps:
      - checkout
  install-yarn:
    executor: node
    steps:
      - node/install-yarn
workflows:
  my-custom-workflow:
    jobs:
      - setup-image
      - install-yarn
      - node/run:
          yarn-run: test