version: 2.1
orbs:
  node: circleci/node@5.0.0
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:node
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/lukeocodes/go-and-git-a-repo/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
  example-job:
    executor: my-custom-executor
    steps:
      - node/install-yarn
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
      - example-job