version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
jobs:
  setup:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # echo Hello, World!
workflows:
  my-custom-workflow:
    jobs:
      - my-job-name